[package]
name = "update"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]

[dependencies]
data = { path = "../data" }
serde = "1"
serde_derive = "1"
serde_json = "1"
web-view = {git = "https://github.com/huytd/web-view"}